### ISSUE TITLE
[TPD0] Can't boot with Interrupt mode

### ISSUE THREAD

**Issue by dreamwhite** [Mateo1234454545/DELL-5570-Hackintosh#1]
Hi @Mateo1234454545,
I have a Dell Inspiron 5370 which has pretty the same firmware as your 5570. I'm trying to enable Interrupt mode on my device, but as I `setup_var 0x272 0x0` (which is GPI0) I get KP. I tried forcing the trackpad to go in Windows mode (OSYS, 0x07DC) but it keeps KP.
Do you have any advice on how to fix it? 
I attach a screenshot of the dumped firmware:

![image](https://user-images.githubusercontent.com/17933708/91062633-3d9f7a80-e62d-11ea-881a-af9b82ea7bb1.png)

What do you think? Should I switch to interrupt mode?
Many thanks

**Comment by Mateo1234454545** [comment]
Yes , switching to interrupt is a good idea.
Don't forget that bios betwwen diffirent models have many changes.

**Comment by dreamwhite** [comment]
Okay but after putting my trackpad mode in interrupt, it kp. Why?

**Comment by Mateo1234454545** [comment]
This guide is for Dell 5570 laptop.

**Comment by dreamwhite** [comment]
> This guide is for Dell 5570 laptop.

Excuse me but that doesn't make sense. I'm not changing a random offset, but the one extracted from MY BIOS which is called "GPIO: Interrupt". So theorically, after changing this offset, my trackpad should go in Interrupt mode, but it keeps KP instead.
What am I doing wrong?

**Comment by dreamwhite** [comment]
I am truly amazed that you clearly ignored my question: why does the system KP when I put the trackpad in "GPIO: Interrupt" mode?
Your reply is "This guide is for Dell 5570 laptop". So, if we want to apply the same logic, when you linked the guide for extracting the BIOS I should have answered you "tHiS gUiDe iS fOr DeLl XpS 9550, NoT fOr YoUr LaPtOp...". Is this even an answer? That's not the goal of "Issues" section of GitHub repositories. I thought you could answer me without this s****y reply, but it doesn't matter: your repository is clearly the representation of lack of MarkDown knowledge, AML knowledge, OpenCore knowledge and finally macOS knowledge... Many renames totally useless, just for cosmetics. I suggest you giving a look at my [repository](https://github.com/dreamwhite/dell-inspiron-5370-hackintosh) and compare it to yours ;)  

P.S. @xLidoni tried your EFI for his Dell Inspiron 5570 and the system KP instantly :) After he tried my EFI, with the minimal requisites, he successfully booted
