### ISSUE TITLE
config.plist

### ISSUE THREAD

**Issue by malefic1950** [Mateo1234454545/DELL-5570-Hackintosh#10]
Ok, first of all thank you for your hard work. I'm still new to hackintoshing but picking it up fairly fast. My problem here is that when I try to boot from usb I get an error " OCS: no schema for KeyMergeTreshold at 2 index. Now, I haven't found anyone with that problem but I read somewhere that "schema" problems are related to bad config.pllist file. I may be wrong here. I was using the python method from Dortania's guide to make usb installer but will try gibMacOS method aswell later to see if it would work. If you have some insight in this problem please do tell. Thanks in advance.

**Comment by beeaniebee** [comment]
I use the OpenCore Configurator app to make the config.plist and sometimes the program doesn't accurately create a config. I will make sure that the config is working and fully configured. Make sure to only use the version of OpenCore that is shipped with the repo, as things will most certainly break if you update OpenCore incorrectly

**Comment by beeaniebee** [comment]
I have verified that KeyMergeThreshold is in the config at the right place and that the config passes the config checker for 0.6.6. Please make sure you're using OpenCore 0.6.6 (it's packaged with the repo's files), and that you're using the most up to date repo files.
