### ISSUE TITLE
unable to boot with some modifications to lates release

### ISSUE THREAD

**Issue by kjoe07** [Mateo1234454545/DELL-5570-Hackintosh#11]
did some mod to the lastest release removed a swapKey and added 4 kext more to adjust to my needs, don't like the command option swap, used to the original mapping get me confused every time so removed and added intelblueTooth kext and intel wifi kext since don't have a Broadcom wifi card yet. but got stuck with some error in and no option is selected to boot, the audio is played but no luck no boot. without the mod the boot works fine except for wifi and bluetooth that no kext loaded checked several times for the error but no luck 

![IMG_0714](https://user-images.githubusercontent.com/3653060/114433511-e9331600-9b8f-11eb-8710-39278c69d265.jpg)
 here is a copy of the OC folder with the config. 
[OC.zip](https://github.com/Mateo1234454545/DELL-5570-Hackintosh/files/6298532/OC.zip)
any Idea what could be wrong with the config, how could I remove the ssdt of key swapt and add the 4 others kext.

**Comment by beeaniebee** [comment]
I think I know what happened. Let me push a quick commit and you can check it with your mods

**Comment by beeaniebee** [comment]
Try it with this update. I think I forgot to update the actual OpenCore.efi file when I updated the files

**Comment by kjoe07** [comment]
Shows the options but stuck on Apple logo

**Comment by beeaniebee** [comment]
Try sending that image again please it looks like it didn't work. Is it a "prohibited" sign?

**Comment by kjoe07** [comment]
Sorry hit send before upload the image just show Apple logo no progress bar at all

**Comment by kjoe07** [comment]
Well now replaced all and booted like charm with a message let me get a picture of it

**Comment by beeaniebee** [comment]
Put "-v" flag in your boot args to turn on verbose boot. If you'd like, you can try to debug the problem yourself by referring to the [OpenCore official guide](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/troubleshooting.html#table-of-contents) or you can send pictures of the boot logs here and I may be able to help.

**Comment by kjoe07** [comment]
Read and is invalid rom message so I could solve guess that is closed this issue thanks a lot

**Comment by kjoe07** [comment]
![39384D64-2F63-4C1D-B0D8-4691A3156146](https://user-images.githubusercontent.com/3653060/114439976-9a897a00-9b97-11eb-9b80-cbc94a1803b6.jpeg)
This one about invalid rom

**Comment by beeaniebee** [comment]
That would just mean you need to setup your SMBIOS with a valid rom. Try using "OpenCore Configurator" to generate a valid SMBIOS once you're into MacOS :)

**Comment by kjoe07** [comment]
Any idea why the command and option keys stay swapped even removing the ssdt keep windows working as command and alt as option

**Comment by beeaniebee** [comment]
I don't know.. @Mateo1234454545 might however, since he was the one who put that in there. I'll do a couple tests and I'll let you know if I figure it out. 

Make sure they're not switched in the MacOS settings!

**Comment by kjoe07** [comment]
Nop ok check it out but only never changed
