### ISSUE TITLE
Add SysReport

### ISSUE THREAD

**Issue by 1alessandro1** [Mateo1234454545/DELL-5570-Hackintosh#12]
Hi, please provide your ACPI Tables with [this sample EFI](https://github.com/utopia-team/opencore-debug/releases/latest) for better documentation of your firmware

**Comment by beeaniebee** [comment]
Can you please elaborate a bit on what you'd like? I've taken a look at the repository, but would appreciate a quick explainer on what you're asking me to do, and how it would help. Thank you!

**Comment by 1alessandro1** [comment]
Hi, to put it simply, to obtain ACPI tables (made from DELL) for this laptop, you should download the sample DEBUG EFI I've attached above, copy that to an USB and boot it: you will see on screen that OpenCore-DEBUG is going to save a copy of the ACPI tables that it finds while reaching the boot menu. Instead of booting something, once you've reached the picker, you should just turn the machine off pressing the power button.

When you've shut down the system, boot with your normal EFI, mount the USB, and next to the EFI folder you will find the Opencore-log.txt and a folder called `SysReport`: zip them both and add them to a folder in your repository, so people can obtain helpful information about this laptop's firmware, whether they have the same machine or a similar one, ACPI tables can help creating ad hoc SSDTs.

**Comment by beeaniebee** [comment]
I see. Is that different from dumping the DSDT tables as shown in the OpenCore Guide?

**Comment by Mateo1234454545** [comment]
[opencore-2021-04-18-234216.txt](https://github.com/Mateo1234454545/DELL-5570-Hackintosh/files/6332429/opencore-2021-04-18-234216.txt)
[SysReport.zip](https://github.com/Mateo1234454545/DELL-5570-Hackintosh/files/6332431/SysReport.zip)

**Comment by 1alessandro1** [comment]
Thanks, you're free to add that to a separate folder, as I did [here](https://github.com/1alessandro1/HP-Pavilion-CE2072NL-macOS/tree/main/Misc/ACPI-Dumps)
