### ISSUE TITLE
No audio in combo jack and weird scroll with trackpad

### ISSUE THREAD

**Issue by kjoe07** [Mateo1234454545/DELL-5570-Hackintosh#13]
using this config with some others kext got no audio from combo jack or mic voice input, also a weird scroll with trackpad, since selecting an item or a window in finder with left click and scrolling, getting to horizontal edge of the track pad and lift the finger to scroll again, make the widows goes back with the finger to begin scrolling.

the refi is the same as https://github.com/Mateo1234454545/DELL-5570-Hackintosh/issues/11

**Comment by beeaniebee** [comment]
First of all, the audio will need CodecCommander.kext installed to /Library/Extensions to work

**Comment by beeaniebee** [comment]
For the second one, is it possible to take a video of the trackpad gesture and the weird behavior? It's hard to visualize what you're describing.

**Comment by kjoe07** [comment]
> First of all, the audio will need CodecCommander.kext installed to /Library/Extensions to work

is not giving you a crash with a unsigned kext in /library/extension since the recommendations to move all kext to /EFI/OC/kext instead of /library/Extension.
a video of the issue

https://user-images.githubusercontent.com/3653060/115314102-9256af00-a142-11eb-9430-21422b496d4e.mov

**Comment by beeaniebee** [comment]
If I understood correctly, you're experiencing a crash when CodecCommander.kext is installed to /Library/Extensions? This kext is unique because it will not work properly if injected by OpenCore. It has to be installed to /Library/Extensions 

I will need to look the files over and test them to see if the trackpad issue is with the efi, or just yours specifically. Please download the latest version of the files, and try to boot with no changes made. If that works, then compare the changes you made to see which one causes the issue.

**Comment by kjoe07** [comment]
No I don’t place it in /library/extension I comment out jut because some apple  restriction with no signed kext in /library/extension since Catalina and the recommended was to move all kext to EFI.

**Comment by beeaniebee** [comment]
It won't let you install the kext to /L/E because there's a problem with the signing certificate? Are you using the most recent version from RehabMan's GitHub repo?

**Comment by beeaniebee** [comment]
> https://user-images.githubusercontent.com/3653060/115314102-9256af00-a142-11eb-9430-21422b496d4e.mov

I am having no issue with the stock, unchanged efi from the repo. I haven't been able to recreate the behavior from my computer. Please try using the efi with no changes to temporarily test if the issue is because of a change you've made

**Comment by kjoe07** [comment]
> It won't let you install the kext to /L/E because there's a problem with the signing certificate? Are you using the most recent version from RehabMan's GitHub repo?

I'm not sure is a version I have from a old version of this repo my guess is from the 1st version @Mateo1234454545 release here, but latter I was not needed, but for me alway needed. I'll try your suggestion and let you know, here's is y full efi folder to let you try the trackpad issue 
https://drive.google.com/file/d/17Zeebep9xig5dSLjACPk-BZtNJuJURd1/view?usp=sharing

**Comment by kjoe07** [comment]
tried the default config and got the same behavior with combo jack and trackpad

**Comment by beeaniebee** [comment]
The efi in the repo currently relies on having CodecCommander installed in /L/E for the jack to work. Please stay tuned for any changes to that current method. 

The trackpad behavior is very odd, and it seems like it could be a misconfigured setting in MacOS or possibly in your trackpad hardware itself

**Comment by kjoe07** [comment]
solved the combo jack with your suggest to install codecComander in /L/E, the track pad issue is not resolved yet very weird,

**Comment by beeaniebee** [comment]
@kjoe07 A testing branch has been made with changes to the AppleALC.kext such that it allows CodecCommander.kext not to be installed on the system at all. If you still prefer to have no kexts installed on the system, you can try this. If you so choose, feedback would be greatly appreciated as to further the progression of this change making it into the master branch.

**Comment by kjoe07** [comment]
I have to remove CodeCommander from /S/L to text this new version in few hours il check and post results here.

**Comment by kjoe07** [comment]
first reboot after delete codeCommander from /L/E and got Audio in headPhone and mic is working to. so this con go to master. let test with second reboot

**Comment by kjoe07** [comment]
comfirmed, second reboot and there is audio and mic is recoding from headPhone jack

**Comment by kjoe07** [comment]
this should no be in here but any one got the fn+f4 -f6 media keys working with my previous config it was working but now not reconigzed.
