### ISSUE TITLE
Issues with the trackpad!

### ISSUE THREAD

**Issue by T0bi-Ethirbirge** [Mateo1234454545/Dell-5570-Hackintosh#2]
I tested your config and It was pretty good but the there are some issues. There is a delay when I scroll or doing any of the gestures. Does it happen to you too?

**Comment by Mateo1234454545** [comment]
No , not at all.
Trackpad in fact is smoother than windows.

**Comment by T0bi-Ethirbirge** [comment]
I have the same laptop as yours except my CPU is "i7-8550U". I suspect that Voodoo2C and Voodoo2CHID kexts are the main cause of the problems.

Everything works fine but it just feels delayed very noticeable delay.
Thanks for the quick replay.
