### ISSUE TITLE
Guide

### ISSUE THREAD

**Issue by malefic1950** [Mateo1234454545/DELL-5570-Hackintosh#2]
Hi, this is not an issue but if you are willing to help me, what should I do with your files? Do I need to follow the complete Open Core guide for me to use this or is there a shorter way? I’m new to this so bear with me.

**Comment by kjoe07** [comment]
you should copy the content in your EFi Folder, and try the the bird editing tool and boot the OS, if already got macOS replacing the content or boot the macOS installer and install macOS.

**Comment by malefic1950** [comment]
Not really answer to my question but thanks anyway.

**Comment by beeaniebee** [comment]
Try checking out the OpenCore install guide [here](https://dortania.github.io/OpenCore-Install-Guide) and the [readme](https://github.com/Mateo1234454545/DELL-5570-Hackintosh/blob/master/README.md) in the files for information you need to get macOS working with OpenCore on your system.
