### ISSUE TITLE
about hdmi

### ISSUE THREAD

**Issue by Largercode** [Mateo1234454545/Dell-5570-hackintosh#2]
Thank you to share, notebook work very well. Hdmi output whether work it? Late I want to buy a monitor

**Comment by Mateo1234454545** [comment]
HDMI works . both video and audio.

**Comment by Largercode** [comment]
Thanks for the reply, what resolution monitor are you using?  Does the UHD620 support 2k or 4k?

**Comment by panique** [comment]
Same laptop here, HDMI works for me too (but with other settings), 4K resolution (not sure which framerate). Also a secondary monitor over USB-C works at the same time!
