### ISSUE TITLE
update to openCore 0.6.3 to boot BigSur

### ISSUE THREAD

**Issue by kjoe07** [Mateo1234454545/DELL-5570-Hackintosh#3]
Update from openCore 0.6.1 to 0.6.3 and lates kext to boot MacOs Big Sur 11.0.1

**Comment by malefic1950** [comment]
I understood what i need to do with BOOT and OC folders but this part of the guide bugs me: Revert back to smbios 15,2. • SSDT's and config.plist optimisation. Can you please explain what this means?

**Comment by kjoe07** [comment]
in your congfig.plist in smb section there is item that is called sabios and is set to 15.4 that's the MacBook Pro model you must change to 15,2 if not.  SSDT are some optimizations done to ssd to boot nice in this laptop model, unless you have another model not the 5570 don't worry about it. and with config.plist nothing to do. just read to update to 0.6.3 that is wat im requesting in this issue since I already tried but no luck updating to 0.6.2 and 0.6.3 first case quit saying open core 0.6.1 and second uncouple of boot.

**Comment by malefic1950** [comment]
Okay, i made the installer and updated kexts and OC like you said. Pasted these 2 folders to the EFI partition on USB but when i click install big sur it just gets stuck on apple logo. Is that due to me not changing the Smbios thing?

**Comment by kjoe07** [comment]
Big Sur the official release not boot with this config openCore 0.6.3 is needed and this config is 0.6.1 so that's why I opened this issue to update to 0.6.3 and latest kext to boot Big Sur.

**Comment by malefic1950** [comment]
I think i didnt update properly, i’ll try again now

**Comment by malefic1950** [comment]
Can you tell me how you updated it cause i think i did it right this time but still hangs on apple logo

**Comment by kjoe07** [comment]
this is not a forum. a issue s to ask to the owner of this repo to update because My self tried and does not work. so waiting for the owner to update. or some one else do it or at lets explain the right procedure to update
