### ISSUE TITLE
Kernel Panic

### ISSUE THREAD

**Issue by BeanieBen9990** [Mateo1234454545/Dell-5570-Hackintosh#3]
I have no idea why, but I just can't get this to work on my computer. Inspiron 5570 just like everything else, and I've followed your guide exactly, and yet I still can't get this to work. Everyone else's clover seems to work just fine, but for some reason mine just won't work. I can't even boot into the installer, as it starts loading kexts and then just reboots. I've trie blocking every single specific kext loaded individually, and the kernel doesn't always panic on the same kext, so I don't think that's the problem. I tried reinstalling clover, redoing everything, and it just does the same thing. The only thing I can think of is that I have a value in my bios wrong, or something that I missed in the guide, but I can't figure it out. OpenCore is my next option but I know more about clover than I do that, so I'm trying hard to fix clover. Any help or suggestions? One question I did have was how to install kexts to l/e, or is that an after-install thing, and wouldn't affect the reason the installer won't boot?

**Comment by BeanieBen9990** [comment]
Solves! New update fixed the kernel patch! For anyone having this problem and not wanting to use new files, it was the DDST.aml in /CLOVER/ACPI/Patched

**Comment by RumiHoo** [comment]
Hi  could you tell me how to find DDST.aml please?   i can't find it in /CLOVER/ACPI/Patched.    my Inspiron 5570 still won't work.    just reboots when i install  Catalina。

**Comment by RumiHoo** [comment]
could you send ur DDST.aml to my email please？we have same Inspiron 5570 so i think it will work .my email is 297310018@qq.com   .Thank you.

**Comment by BeanieBen9990** [comment]
If you don’t have a DDST.aml in your EFI/CLOVER/ACPI/patched then you should be all fine. Try making a clover boot usb with just the generic files from the repo (assuming you configure SMBIOS the same etc) and see how that works.
