### ISSUE TITLE
dell 5558 looping

### ISSUE THREAD

**Issue by marcelloinfoweb** [Mateo1234454545/Dell-5570-hackintosh#4]
I changed the EFI directory files, but did not install, just rebooted, what could be happening? I have already inserted several tags and configured the bios, I am using the version of Olarila Mojave 10.14.5.

Dell Inspiron 15 5558 b40 Notebook

**Comment by Mateo1234454545** [comment]
Different laptop , different specs.

**Comment by marcelloinfoweb** [comment]
Damn, what a lazy explanation.
