### ISSUE TITLE
Trackpad not working out of the box?

### ISSUE THREAD

**Issue by BeanieBen9990** [Mateo1234454545/Dell-5570-Hackintosh#4]
I tried the new clover config on Mojave and everything works amazing right out of the box! Wonderful experience compared to the pain of the install and original files, which had many problems for me on my setup. Unfortunately, when I booted up Catalina, the trackpad isn't working! Everything else works great, even graphics, keyboard, and sound, which were huge problems for me before. I will do some quick troubleshooting and see if I can fix it, but seeing as you (might have) listened to my problem last time with the kernel panic, I was wondering what kind of fix you may have for me. I will try the OC just in case too, just to help out. Thanks for the hard work on this, as you've made at least my life a whole lot easier trying to hackintosh our laptop. :)

**Comment by Mateo1234454545** [comment]
Be sure to use the trackpad kexts included in my repo , because the original ones from alexandred repo have problems with Catalina.
Also ,remember to rebuild cache with sudo kextcache -i /   and reboot after any software update.

**Comment by BeanieBen9990** [comment]
SOLVED! Issue fixed by placing IOGraphicsFamily.kext from MacOS’ S/L/E to clovers’ EFI/CLOVER/kexts
