### ISSUE TITLE
ACPI Patches being applied in other operating systems

### ISSUE THREAD

**Issue by beeaniebee** [Mateo1234454545/DELL-5570-Hackintosh#5]
Hey Mateo! Just letting you know about something that should be added in the ACPI patches. In [this](https://github.com/acidanthera/OpenCorePkg/pull/147#issuecomment-750069862) GitHub reply about an issue I had with my brightness keys not showing up in linux when booted with OpenCore, I learned that there should be a check to make sure the operating system is "Darwin" (macOS) since they're your ACPI patches and you know much more about ASL than me, I figured I'd try to fix the brightness ACPI patch on my own for me, and let you know about what should be done/added so you can take care of it better then I can. Thank you!

**Comment by Mateo1234454545** [comment]
Thank you for your feedback.

The EFI in this repo is rather old. I've changed many things and my laptop is more stable an functional than ever.
Unfortunately i don't have the time to update repo. My work comes first. That's the reason I've added donations.

There is no need to use ssdt for brightness anymore. there is now a BrightnessKeys.kext that takes care of that. 
And I don't really see the point of booting to Linux/Windows through Opencore. Just use BIOS entry for that.

Thank you again. Keep up the good work.

**Comment by beeaniebee** [comment]
If you'd like, you could send me the files, add me as a contributeur, and I could update the repo! I'm very thankful of the work you've put into this project and I would love to to help you out if I could. I have experience with GitHub repo managing and I should be able to do it no sweat. If not, that's alright. I would seriously be grateful if you sent over your OC folder though, as that would be super helpful especially for that brightness keys issue.

**Comment by Mateo1234454545** [comment]
Here you go.
[EFI copy.zip](https://github.com/Mateo1234454545/DELL-5570-Hackintosh/files/5757963/EFI.copy.zip)

**Comment by beeaniebee** [comment]
Thank you so much! Will get it pushed soon!
