### ISSUE TITLE
Netflix and iTunes DRM content

### ISSUE THREAD

**Issue by BeanieBen9990** [Mateo1234454545/Dell-5570-Hackintosh#5]
Is anyone else having trouble playing Netflix in safari or purchased iTunes shows/movies or any other DRM content? I don’t know what to do about it because most of the problems I’ve found researching it have been using external GPU’s and the fixes pertain only to the GPU’s. Any help?

**Comment by Mateo1234454545** [comment]
There is currently no way to watch DRM protected content on Safari without AMD card.
Use Chrome instead.

**Comment by BeanieBen9990** [comment]
Thanks!
