### ISSUE TITLE
The EFI is not bootable

### ISSUE THREAD

**Issue by nino-joy** [Mateo1234454545/DELL-5570-Hackintosh#6]
While booting, in place of the boot selection menu, a black screen appears and nothing happens further.

**Comment by kjoe07** [comment]
i have the same result the update  day and reverted to my previous version and update to open core version the Mac id is not suitable for the 5570 with i5 with 8th gen intel but maybe there are some optimization done to boot with that config that the standard model does not fit

**Comment by nino-joy** [comment]
> i have the same result the update day and reverted to my previous version and update to open core version the Mac id is not suitable for the 7750 with i5 with 8th gen intel but maybe there are some optimization done to boot with that config that the standard model does not fit

This EFI is for the 5570 right?🙄

**Comment by kjoe07** [comment]
Indeed a typo error

**Comment by beeaniebee** [comment]
When you put the EFI into your system, what did you change to configure it for your system? Anything?

**Comment by kjoe07** [comment]
None

**Comment by nino-joy** [comment]
> When you put the EFI into your system, what did you change to configure it for your system? Anything?

Didn't do anything.

**Comment by nino-joy** [comment]
Just for a trial, I used the EFI which was provided to @BeanieBen9990 from @Mateo1234454545 in a previously closed issue and it booted perfectly fine and currently running my macOS on it. So, it might be something @BeanieBen9990 added later on in the EFI (Not sure as I am not an expert in this).

[EFI copy.zip](https://github.com/Mateo1234454545/DELL-5570-Hackintosh/files/5822610/EFI.copy.zip)

**Comment by beeaniebee** [comment]
Try unchecking ReleaseUSBOwnership in UEFI/Quirks. I was having the same issue with my system when it was off, but Mateo didn't have an issue either way. It's possible it's a kind of per system basis. Do you have an nvme and a sata drive in your machine?

**Comment by nino-joy** [comment]
> Try unchecking ReleaseUSBOwnership in UEFI/Quirks. I was having the same issue with my system when it was off, but Mateo didn't have an issue either way. It's possible it's a kind of per system basis. Do you have an nvme and a sata drive in your machine?

I tried unchecking ReleaseUSBOwnership and now it shows this:

![OC boot error](https://user-images.githubusercontent.com/44795916/104798124-1028b880-57ea-11eb-9b03-721b7f0a75cc.jpeg)

**Comment by nino-joy** [comment]
> Try unchecking ReleaseUSBOwnership in UEFI/Quirks. I was having the same issue with my system when it was off, but Mateo didn't have an issue either way. It's possible it's a kind of per system basis. Do you have an nvme and a sata drive in your machine?

These are the drives present in my system:
![Screen Shot 2021-01-16 at 11 02 42 AM](https://user-images.githubusercontent.com/44795916/104798185-5d0c8f00-57ea-11eb-8b12-b563d34a6fda.png)

**Comment by nino-joy** [comment]
> Try unchecking ReleaseUSBOwnership in UEFI/Quirks. I was having the same issue with my system when it was off, but Mateo didn't have an issue either way. It's possible it's a kind of per system basis. Do you have an nvme and a sata drive in your machine?

These are the drives present in my system:

![Screen Shot 2021-01-16 at 11 03 45 AM](https://user-images.githubusercontent.com/44795916/104798208-83322f00-57ea-11eb-9fa2-b50c48f04d81.png)

**Comment by beeaniebee** [comment]
Make sure to use the most recent version of the files. You're using an old version in which those undefined values were added in accordance with the OpenCore documentation. After pulling the most recent files and unchecking ReleaseUSBOwnership, does it boot?

**Comment by beeaniebee** [comment]
> Make sure to use the most recent version of the files. You're using an old version in which those undefined values were added in accordance with the OpenCore documentation. After pulling the most recent files and unchecking ReleaseUSBOwnership, does it boot?

@nino-joy does this fix the problem?

**Comment by MartinsMickus** [comment]
> While booting, in place of the boot selection menu, a black screen appears and nothing happens further.

@nino-joy I had this kind of problem when tried to install Hackintosh on Dell Inspiron One 2330. Eventually the problem was AudioDxe.efi driver in drivers folder. I found it out while leaving computer for very long and it successfully booted xD. Then I started to dig into problem and found out that one of the drivers caused it. When removed AudioDxe problem was fixed.

**Comment by dreamwhite** [comment]
Honestly, this EFI is just a bunch of random ACPI patches, result of total inexperience in ACPI and OpenCore configuration ._.
If you want an advice, start off dortania's guide, add the minimum required patches, then start deep-investigating each issue until you find a way to get everything working.

e.g. I documented each change for my laptop until it's perfectly working. For more infos check [here](https://github.com/dreamwhite/dell-inspiron-5370-hackintosh/)

**Comment by Mateo1234454545** [comment]
Some are cosmetics yes  , random no.
Which patch do you think is random?

e.g. my laptop is working perfectly too. Everything works as a real mac. Still no competition though.

**Comment by beeaniebee** [comment]
@nino-joy @kjoe07

I have thoroughly tested and refined the config in the upcoming update to OC 0.6.7, soon to be merged with master. Please make sure that the EFI boots by using the 0.6.7-testing branch or by waiting until the changes are merged with master. Please note that while it may boot, you should update the config.plist file to have a customized serial number, SMBIOS, and other similar info in the PlatformInfo section of the plist. You can also use a program like OpenCore Configurator to do this automatically. After verifying that the new files will boot, please let me know here and either update with additional info to find the root of the problem, or close the issue. Thank you for your support

**Comment by nino-joy** [comment]
> @nino-joy @kjoe07
> 
> I have thoroughly tested and refined the config in the upcoming update to OC 0.6.7, soon to be merged with master. Please make sure that the EFI boots by using the 0.6.7-testing branch or by waiting until the changes are merged with master. Please note that while it may boot, you should update the config.plist file to have a customized serial number, SMBIOS, and other similar info in the PlatformInfo section of the plist. You can also use a program like OpenCore Configurator to do this automatically. After verifying that the new files will boot, please let me know here and either update with additional info to find the root of the problem, or close the issue. Thank you for your support

I tried booting the test branch and now the black screen error is gone and the picker appears. But a boot issue still persists and whatever mac os I try to boot results in the following stop-sign error. I even tried a fresh installer of mac os big sur which showed up in the picker, but selecting it showed the same stop-sign error.

![WhatsApp Image 2021-03-19 at 8 49 38 AM](https://user-images.githubusercontent.com/44795916/111727229-80a69100-8890-11eb-9f4a-2efe00caeef7.jpeg)
![WhatsApp Image 2021-03-19 at 8 49 39 AM](https://user-images.githubusercontent.com/44795916/111727242-856b4500-8890-11eb-8937-1acd3f0bc4c0.jpeg)

**Comment by beeaniebee** [comment]
I've notified that happens when you don't have the smbios configured correctly. Make sure you've got an smbios of MacBookPro16,3 and try again

**Comment by nino-joy** [comment]
I tried with smbios of MacBook16,4 and didnt work. Let me try MacBook16,3

**Comment by nino-joy** [comment]
> > @nino-joy @kjoe07
> > I have thoroughly tested and refined the config in the upcoming update to OC 0.6.7, soon to be merged with master. Please make sure that the EFI boots by using the 0.6.7-testing branch or by waiting until the changes are merged with master. Please note that while it may boot, you should update the config.plist file to have a customized serial number, SMBIOS, and other similar info in the PlatformInfo section of the plist. You can also use a program like OpenCore Configurator to do this automatically. After verifying that the new files will boot, please let me know here and either update with additional info to find the root of the problem, or close the issue. Thank you for your support
> 
> I tried booting the test branch and now the black screen error is gone and the picker appears. But a boot issue still persists and whatever mac os I try to boot results in the following stop-sign error. I even tried a fresh installer of mac os big sur which showed up in the picker, but selecting it showed the same stop-sign error.
> 
> ![WhatsApp Image 2021-03-19 at 8 49 38 AM](https://user-images.githubusercontent.com/44795916/111727229-80a69100-8890-11eb-9f4a-2efe00caeef7.jpeg)
> ![WhatsApp Image 2021-03-19 at 8 49 39 AM](https://user-images.githubusercontent.com/44795916/111727242-856b4500-8890-11eb-8937-1acd3f0bc4c0.jpeg)

Same error persists even after MacBookPro16,3. Personally I don't think it's a SMBIOS issue because even a bootable installer of MacOS Big Sur which I made didn't boot. It gave the same error. But it boots fine in the previous builds. Also I'm currently on OC 0.6.2 build which works perfectly fine. Think it was made by @Mateo1234454545 .

**Comment by dreamwhite** [comment]
> > > @nino-joy @kjoe07
> > > I have thoroughly tested and refined the config in the upcoming update to OC 0.6.7, soon to be merged with master. Please make sure that the EFI boots by using the 0.6.7-testing branch or by waiting until the changes are merged with master. Please note that while it may boot, you should update the config.plist file to have a customized serial number, SMBIOS, and other similar info in the PlatformInfo section of the plist. You can also use a program like OpenCore Configurator to do this automatically. After verifying that the new files will boot, please let me know here and either update with additional info to find the root of the problem, or close the issue. Thank you for your support
> > 
> > 
> > I tried booting the test branch and now the black screen error is gone and the picker appears. But a boot issue still persists and whatever mac os I try to boot results in the following stop-sign error. I even tried a fresh installer of mac os big sur which showed up in the picker, but selecting it showed the same stop-sign error.
> > ![WhatsApp Image 2021-03-19 at 8 49 38 AM](https://user-images.githubusercontent.com/44795916/111727229-80a69100-8890-11eb-9f4a-2efe00caeef7.jpeg)
> > ![WhatsApp Image 2021-03-19 at 8 49 39 AM](https://user-images.githubusercontent.com/44795916/111727242-856b4500-8890-11eb-8937-1acd3f0bc4c0.jpeg)
> 
> Same error persists even after MacBookPro16,3. Personally I don't think it's a SMBIOS issue because even a bootable installer of MacOS Big Sur which I made didn't boot. It gave the same error. But it boots fine in the previous builds. Also I'm currently on OC 0.6.2 build which works perfectly fine. Think it was made by @Mateo1234454545 .

Wait what's the purpose of having MacBookPro16,3 with a Dell Inspiron 5570 which has a 8th gen CPU?
I don't wanna insult the owner of the EFI too much but trust me, it's crap af. I tried previously his EFI but I always had the famous "deny sign" like you had. I highly suggest starting from a scratch EFI (like the 5370 one on my repositories list) and removing the stuff you don't need (e.g. MmioWhitelist + DevirtualiseMmio, kext for the broadcom ecc)

**Comment by beeaniebee** [comment]
> > > @nino-joy @kjoe07
> 
> > > I have thoroughly tested and refined the config in the upcoming update to OC 0.6.7, soon to be merged with master. Please make sure that the EFI boots by using the 0.6.7-testing branch or by waiting until the changes are merged with master. Please note that while it may boot, you should update the config.plist file to have a customized serial number, SMBIOS, and other similar info in the PlatformInfo section of the plist. You can also use a program like OpenCore Configurator to do this automatically. After verifying that the new files will boot, please let me know here and either update with additional info to find the root of the problem, or close the issue. Thank you for your support
> 
> > 
> 
> > I tried booting the test branch and now the black screen error is gone and the picker appears. But a boot issue still persists and whatever mac os I try to boot results in the following stop-sign error. I even tried a fresh installer of mac os big sur which showed up in the picker, but selecting it showed the same stop-sign error.
> 
> > 
> 
> > ![WhatsApp Image 2021-03-19 at 8 49 38 AM](https://user-images.githubusercontent.com/44795916/111727229-80a69100-8890-11eb-9f4a-2efe00caeef7.jpeg)
> 
> > ![WhatsApp Image 2021-03-19 at 8 49 39 AM](https://user-images.githubusercontent.com/44795916/111727242-856b4500-8890-11eb-8937-1acd3f0bc4c0.jpeg)
> 
> 
> 
> Same error persists even after MacBookPro16,3. Personally I don't think it's a SMBIOS issue because even a bootable installer of MacOS Big Sur which I made didn't boot. It gave the same error. But it boots fine in the previous builds. Also I'm currently on OC 0.6.2 build which works perfectly fine. Think it was made by @Mateo1234454545 .

I will look further into this bug. I only encountered it yesterday when debugging the efi for your issue with it not booting. The efi is modeled similar to my efi which never once had that issue. However, it did have this issue once I removed the platforminfo. 

Looking into the platforminfo bug, I just noticed that config still doesn't have the platforminfo in the config that I intended it to. I have no idea why this is happening but I'll test later and verify 100% that the efi is working straight out of the box on my laptop. 

I do apologize about the inconvenience of it not working however.

**Comment by nino-joy** [comment]
> > > > @nino-joy @kjoe07
> > 
> > 
> > > > I have thoroughly tested and refined the config in the upcoming update to OC 0.6.7, soon to be merged with master. Please make sure that the EFI boots by using the 0.6.7-testing branch or by waiting until the changes are merged with master. Please note that while it may boot, you should update the config.plist file to have a customized serial number, SMBIOS, and other similar info in the PlatformInfo section of the plist. You can also use a program like OpenCore Configurator to do this automatically. After verifying that the new files will boot, please let me know here and either update with additional info to find the root of the problem, or close the issue. Thank you for your support
> > 
> > 
> > > 
> > 
> > 
> > > I tried booting the test branch and now the black screen error is gone and the picker appears. But a boot issue still persists and whatever mac os I try to boot results in the following stop-sign error. I even tried a fresh installer of mac os big sur which showed up in the picker, but selecting it showed the same stop-sign error.
> > 
> > 
> > > 
> > 
> > 
> > > ![WhatsApp Image 2021-03-19 at 8 49 38 AM](https://user-images.githubusercontent.com/44795916/111727229-80a69100-8890-11eb-9f4a-2efe00caeef7.jpeg)
> > 
> > 
> > > ![WhatsApp Image 2021-03-19 at 8 49 39 AM](https://user-images.githubusercontent.com/44795916/111727242-856b4500-8890-11eb-8937-1acd3f0bc4c0.jpeg)
> > 
> > 
> > Same error persists even after MacBookPro16,3. Personally I don't think it's a SMBIOS issue because even a bootable installer of MacOS Big Sur which I made didn't boot. It gave the same error. But it boots fine in the previous builds. Also I'm currently on OC 0.6.2 build which works perfectly fine. Think it was made by @Mateo1234454545 .
> 
> I will look further into this bug. I only encountered it yesterday when debugging the efi for your issue with it not booting. The efi is modeled similar to my efi which never once had that issue. However, it did have this issue once I removed the platforminfo.
> 
> Looking into the platforminfo bug, I just noticed that config still doesn't have the platforminfo in the config that I intended it to. I have no idea why this is happening but I'll test later and verify 100% that the efi is working straight out of the box on my laptop.
> 
> I do apologize about the inconvenience of it not working however.

Keep up the work brother. No pressure!

**Comment by Mateo1234454545** [comment]
MacBooPro 16,3 uses a I5-8257U  https://everymac.com/systems/apple/macbook_pro/specs/macbook-pro-core-i5-1.4-quad-core-13-2020-2-thunderbolt-3-ports-scissor-specs.html , which is a 8th Generation Intel® Core™ i5 Processor https://ark.intel.com/content/www/us/en/ark/products/191067/intel-core-i5-8257u-processor-6m-cache-up-to-3-90-ghz.html , like DELL 5570 has.

I agree with you. My efi is crap. But then why are you keep watching this thread?
And for the first and last time...

I'm glad that after a lot of work I have a 400euros laptop working as close to a MacBook Pro as possible.
And i share my efi to anyone wanna try.
I don't owe anything to anyone.

> Wait what's the purpose of having MacBookPro16,3 with a Dell Inspiron 5570 which has a 8th gen CPU?
> I don't wanna insult the owner of the EFI too much but trust me, it's crap af. I tried previously his EFI but I always had the famous "deny sign" like you had. I highly suggest starting from a scratch EFI (like the 5370 one on my repositories list) and removing the stuff you don't need (e.g. MmioWhitelist + DevirtualiseMmio, kext for the broadcom ecc)

**Comment by dreamwhite** [comment]
Well to be fair you should check if the frequencies are the same for both SMBIOSes (MBP15,2 and MBP16,3). Despite they're classified as Coffee Lake CPUs, the frequencies are a little bit different :") 
By the way, I don't wanna create a flame :")
Cheers by my Dell Inspiron 5370 paid 600 EUR + 150 EUR of NVMe + DW1830 about 2 year ago

**Comment by Mateo1234454545** [comment]
> Well to be fair you should check if the frequencies are the same for both SMBIOSes (MBP15,2 and MBP16,3). Despite they're classified as Coffee Lake CPUs, the frequencies are a little bit different :")
> By the way, I don't wanna create a flame :")
> Cheers by my Dell Inspiron 5370 paid 600 EUR + 150 EUR of NVMe + DW1830 about 2 year ago

Yes , indeed. Frequencies are a bit diffirent. And you know what? MBP16,3 is closer to my Intel 5280u than MBP15,2. 
System is snappier and battery about the same.

Are you feeling lonely on your own github page ? If so , you are always welcome here.

**Comment by Mateo1234454545** [comment]
> Well to be fair you should check if the frequencies are the same for both SMBIOSes (MBP15,2 and MBP16,3). Despite they're classified as Coffee Lake CPUs, the frequencies are a little bit different :")
> By the way, I don't wanna create a flame :")
> Cheers by my Dell Inspiron 5370 paid 600 EUR + 150 EUR of NVMe + DW1830 about 2 year ago

Yes , indeed. Frequencies are a bit diffirent. And you know what? MBP16,3 is closer to my Intel 5280u than MBP15,2. 
System is snappier and battery about the same.

Are you feeling lonely on your own github page ? If so , you are always welcome here.

**Comment by dreamwhite** [comment]
Regarding the battery what's the average battery life from 100%? I'm thinking of replacing my battery but I don't know if it's worth it at the moment.
Anyways don't worry, I don't need charity from your repo. What really matters is:

- config.plist compliant to OpenCorePkg (did a quick check on both your git branches and there are a few errors :/)
- added only the necessary ACPI patches (SSDT and renames by checking the HEX data), without adding random SSDTs (you'd need prob just half of them but okay)
- having the correct the kext order which is compliant to OpenCorePkg specs

To be fair, dear Mateo, I'd rather study a little bit more and then I'll give advices. I'm not a professional hackintosher, neither I'll want to be in the future, but hey, why doing misinformation? 
If you wanna propose something please furnish proofs of it, rather than adding random stuff without giving any kind of info about it ^^ 

e.g. SSDT-DMAC. What does it do? Is it necessary or can we easily ignore it? 

I hope that you'll read those words in a peaceful way, rather than seeing them as a personal attack :")  
Cheers,
dreamwhite

**Comment by beeaniebee** [comment]
> Regarding the battery what's the average battery life from 100%? I'm thinking of replacing my battery but I don't know if it's worth it at the moment.
> 
> Anyways don't worry, I don't need charity from your repo. What really matters is:
> 
> 
> 
> - config.plist compliant to OpenCorePkg (did a quick check on both your git branches and there are a few errors :/)
> 
> - added only the necessary ACPI patches (SSDT and renames by checking the HEX data), without adding random SSDTs (you'd need prob just half of them but okay)
> 
> - having the correct the kext order which is compliant to OpenCorePkg specs
> 
> 
> 
> To be fair, dear Mateo, I'd rather study a little bit more and then I'll give advices. I'm not a professional hackintosher, neither I'll want to be in the future, but hey, why doing misinformation? 
> 
> If you wanna propose something please furnish proofs of it, rather than adding random stuff without giving any kind of info about it ^^ 
> 
> 
> 
> e.g. SSDT-DMAC. What does it do? Is it necessary or can we easily ignore it? 
> 
> 
> 
> I hope that you'll read those words in a peaceful way, rather than seeing them as a personal attack :")  
> 
> Cheers,
> 
> dreamwhite
> 
> 

If you're having issues with the config or files, please feel free to make an issue and keep it in there please. I assure you I'm working on getting everything working as best as I can, so if you could keep conversation out of another's issue that would be preferable.

**Comment by dreamwhite** [comment]
> > Regarding the battery what's the average battery life from 100%? I'm thinking of replacing my battery but I don't know if it's worth it at the moment.
> > Anyways don't worry, I don't need charity from your repo. What really matters is:
> > 
> > * config.plist compliant to OpenCorePkg (did a quick check on both your git branches and there are a few errors :/)
> > * added only the necessary ACPI patches (SSDT and renames by checking the HEX data), without adding random SSDTs (you'd need prob just half of them but okay)
> > * having the correct the kext order which is compliant to OpenCorePkg specs
> > 
> > To be fair, dear Mateo, I'd rather study a little bit more and then I'll give advices. I'm not a professional hackintosher, neither I'll want to be in the future, but hey, why doing misinformation?
> > If you wanna propose something please furnish proofs of it, rather than adding random stuff without giving any kind of info about it ^^
> > e.g. SSDT-DMAC. What does it do? Is it necessary or can we easily ignore it?
> > I hope that you'll read those words in a peaceful way, rather than seeing them as a personal attack :")
> > Cheers,
> > dreamwhite
> 
> If you're having issues with the config or files, please feel free to make an issue and keep it in there please. I assure you I'm working on getting everything working as best as I can, so if you could keep conversation out of another's issue that would be preferable.

Sure :")
I'm a little bit busy in those days, but I can try creating a fork of your repo and try to "optimize" it, according to the compliance provided by OpenCorePkg :)
Hope you'll appreciate it

p.s. may you gently attach your SysReport dump?

**Comment by Mateo1234454545** [comment]
@dreamwhite , my battery lasts about 4-4.5 hours on average with mild use , like browsing , music ,office work etc.
About 1hour longer than windows.

If you want proof about how good this efi realy is , take a look and check if it can get any better.
[Screen Shot 2021-03-20 at 20.36.53.pdf](https://github.com/Mateo1234454545/DELL-5570-Hackintosh/files/6176185/Screen.Shot.2021-03-20.at.20.36.53.pdf)

**Comment by dreamwhite** [comment]
> @dreamwhite , my battery lasts about 4-4.5 hours on average with mild use , like browsing , music ,office work etc.
> About 1hour longer than windows.

Oh, nice, what's the battery full charge capacity? I have 1190 mAh (sadly) and I still don't get if this is a wrong reading, or is the real tho.

> If you want proof about how good this efi realy is , take a look and check if it can get any better.
> [Screen Shot 2021-03-20 at 20.36.53.pdf](https://github.com/Mateo1234454545/DELL-5570-Hackintosh/files/6176185/Screen.Shot.2021-03-20.at.20.36.53.pdf)

Regarding Intel Power Gadget are you on the latest version (3.7.0)? 
I have the following stats and yours seems a little bit weird 😅

![image](https://user-images.githubusercontent.com/17933708/111882183-72ea2c00-89b4-11eb-9f34-a86edf13e0c1.png)

Am I the only one who has a correct reading or what?

**Comment by kjoe07** [comment]
> MacBooPro 16,3 uses a I5-8257U https://everymac.com/systems/apple/macbook_pro/specs/macbook-pro-core-i5-1.4-quad-core-13-2020-2-thunderbolt-3-ports-scissor-specs.html , which is a 8th Generation Intel® Core™ i5 Processor https://ark.intel.com/content/www/us/en/ark/products/191067/intel-core-i5-8257u-processor-6m-cache-up-to-3-90-ghz.html , like DELL 5570 has.
> 
> I agree with you. My efi is crap. But then why are you keep watching this thread?
> And for the first and last time...
> 
> I'm glad that after a lot of work I have a 400euros laptop working as close to a MacBook Pro as possible.
> And i share my efi to anyone wanna try.
> I don't owe anything to anyone.
> 
> > Wait what's the purpose of having MacBookPro16,3 with a Dell Inspiron 5570 which has a 8th gen CPU?
> > I don't wanna insult the owner of the EFI too much but trust me, it's crap af. I tried previously his EFI but I always had the famous "deny sign" like you had. I highly suggest starting from a scratch EFI (like the 5370 one on my repositories list) and removing the stuff you don't need (e.g. MmioWhitelist + DevirtualiseMmio, kext for the broadcom ecc)

sorry the interruption but the 5570 i5 is not really coffee lake one is really a Kaby-lake-R CPU under i5 5280U the first version were just clarified like that, in www.tonymacx86.com in delete thread about this laptop mr RehaBMan let clear that this laptop were not a truly Coffeys lake, and that important. maybe that because mine laptop with this config is not available to boot. but im not an expert just following other work and great one by the way

**Comment by Mateo1234454545** [comment]
@dreamwhite , I still use version 3.5.5. I don't like the layout of latest versions.

My battery has 2155mAh. I'm not sure if it is real , either.
My guess is that there is a bug with Dell bios , many Dell users are complaining about that.
Try this. Full charge your battery and then let it dry out completely (leave it open one night on bios screen with sceen brightness at full). Then charge it fully again and see what happens.

**Comment by Mateo1234454545** [comment]
You are free to try, but believe me , there is no room left for "optimisation". 

This EFI is the best for this laptop. And one of the best in hackintosh world. I mean it. Everything is working not just OK , but great. Anyway , as great at hackintosh could be.

Removing uneccessary (cosmetic) patches won't do anything in real life usage. Would be just a cosmetic removal.
But again ... try.

By the way , the EFI I really use has some diffirences from the one uploaded here. 

> I'm a little bit busy in those days, but I can try creating a fork of your repo and try to "optimize" it, according to the compliance provided by OpenCorePkg :)
> Hope you'll appreciate it

**Comment by nino-joy** [comment]
https://github.com/Doregon/Inspiron-5570-KBR-Hackintosh

Guys, please refer the above repo which works perfectly. Even the sleep functionality works! Awesome.

**Comment by beeaniebee** [comment]
> https://github.com/Doregon/Inspiron-5570-KBR-Hackintosh
> 
> 
> 
> Guys, please refer the above repo which works perfectly. Even the sleep functionality works! Awesome. 

If you were having issues with sleep/hibernation before let me know. Sleep/hibernation works fine for me.

**Comment by nino-joy** [comment]
> > https://github.com/Doregon/Inspiron-5570-KBR-Hackintosh
> > Guys, please refer the above repo which works perfectly. Even the sleep functionality works! Awesome.
> 
> If you were having issues with sleep/hibernation before let me know. Sleep/hibernation works fine for me.

Sleep didn't work for me from the beginning. The system would just black out ( I think it's known as panic state) and would require a force restart to come back.

**Comment by beeaniebee** [comment]
> > > https://github.com/Doregon/Inspiron-5570-KBR-Hackintosh
> 
> > > Guys, please refer the above repo which works perfectly. Even the sleep functionality works! Awesome.
> 
> > 
> 
> > If you were having issues with sleep/hibernation before let me know. Sleep/hibernation works fine for me.
> 
> 
> 
> Sleep didn't work for me from the beginning. The system would just black out ( I think it's known as panic state) and would require a force restart to come back. 

Hmm that's odd. I have sleep, power nap, and hibernation completely working on mine atm. Do you happen to have the model with the cd drive?

**Comment by kjoe07** [comment]
I have the cd model sleep works with 8% battery lost in 8 to 10 hours sleeping, some times I hear the mechanical hdd sound in sleep but just few times, my battery does not lasts as long as @Mateo1234454545 only 2 hours and maybe with low britght to 2,5 but never got to 3

**Comment by beeaniebee** [comment]
@nino-joy I think I've finally figured out what was going wrong with the changes not saved in the efi. Please check out the testing branch and confirm that the config is working out of the box, without that error symbol.

**Comment by beeaniebee** [comment]
Closing as I have fully verified that the EFI is bootable and works fine.
