### ISSUE TITLE
EFI clarifications

### ISSUE THREAD

**Issue by dreamwhite** [Mateo1234454545/DELL-5570-Hackintosh#7]
Dear Mateo,
may I gently ask you where did this patch come from? Eventually do you have any kind of documentation I can read?

- [patch](https://github.com/Mateo1234454545/DELL-5570-Hackintosh/blob/master/OC/config.plist#L438-L448)

**Comment by Mateo1234454545** [comment]
It was a pull request on dortania I think , explaining the steps to find out the correct value for each laptop.
Don't remember the link , if you search through dortania repo , you will find it.
