### ISSUE TITLE
Trackpad on 10.15.3

### ISSUE THREAD

**Issue by BeanieBen9990** [Mateo1234454545/Dell-5570-Hackintosh#7]
The trackpad is stuttering after upgrade to 10.15.3. Any help?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Mateo1234454545** [comment]
If you followed the guide it shouldn't.

**Comment by BeanieBen9990** [comment]
>If you followed the guide it shouldn't.

@Mateo1234454545 it seems like restarting worked.. thought I had. Maybe it needed a second one. Working fine now

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
