### ISSUE TITLE
Problem right after selecting the USB stick while trying to install Big Sur

### ISSUE THREAD

**Issue by florea326** [Mateo1234454545/DELL-5570-Hackintosh#8]
Please Help! I used exactly the files given, but right after selecting the bootable media, it gives me these 2 errors:

OCS: No schema for PickerVariant at 6 index, context <Boot>!
OCS: No schema for SetupDelay at 6 index, context <Audio>!

and for the bios, i just turned off secure boot and switched it to ahci. I'm not rlly sure how to solve it. I'm trying to install Macos Big Sur

**Comment by Mateo1234454545** [comment]
You are probably using another opencore version than this repo.
Just use exactly the files given from all the folders.
If you later want to upgrade the opencore version, you need to make adjuments to config.plist.

**Comment by beeaniebee** [comment]
I have just seen that OpenCore was updated recently and I had missed it. Will update and if this bug is within the files, then it'll be fixed very soon. Stay tuned

**Comment by beeaniebee** [comment]
@florea326 I've added a branch, named 0.6.6-testing that you are free to try out. Let me know if there's any problems and it will soon be merged with master
