### ISSUE TITLE
The EFI still not bootable 

### ISSUE THREAD

**Issue by RumiHoo** [Mateo1234454545/DELL-5570-Hackintosh#9]
HI thank you for ur sharing ,when i use this EFI, its still not bootable .same issue like 0.64 version. when i use this EFI with usb stick,while booting，still a black screen appears and nothing happens further。maybe we have different BIOS setting，could you please share ur BIOS setting picture for us ？second question，do i need any adjustment when i use this EFI.

**Comment by beeaniebee** [comment]
Did you set the bios settings using the guide in the README? It used to say that MacOS would not boot without these changes, and for me that still applies to my computer at least.

**Comment by RumiHoo** [comment]
i did all that settings using the guide in the README.  but its still appears a black screen without anything。

**Comment by RumiHoo** [comment]
![IMG_6803](https://user-images.githubusercontent.com/56855481/109774300-288a5080-7c3b-11eb-8379-83bde719f9fc.JPG)

**Comment by beeaniebee** [comment]
@RumiHoo 

I have thoroughly tested and refined the config in the upcoming update to OC 0.6.7, soon to be merged with master. Please make sure that the EFI boots by using the 0.6.7-testing branch or by waiting until the changes are merged with master. Please note that while it may boot, you should update the config.plist file to have a customized serial number, SMBIOS, and other similar info in the PlatformInfo section of the plist. You can also use a program like OpenCore Configurator to do this automatically. After verifying that the new files will boot, please let me know here and either update with additional info to find the root of the problem, or close the issue. Thank you for your support

**Comment by beeaniebee** [comment]
Closing as I have fully verified that the EFI is bootable and works fine.
